# Grafana 中文配置
[users]
default_language = zh-Hans

[date_formats]
full_date = YYYY年MM月DD日 HH:mm:ss
interval_second = HH:mm:ss
interval_minute = HH:mm
interval_hour = MM月DD日 HH:mm
interval_day = MM月DD日
interval_month = YYYY年MM月
interval_year = YYYY年
